<?php
/**
 * Co-Curricular Module Notification & FCM Data Access
 */
declare(strict_types=1);

if (file_exists(__DIR__ . '/../config/cocurricular-config.php')) {
    require_once __DIR__ . '/../config/cocurricular-config.php';
}

require_once __DIR__ . '/cocurricular-db.php';

function cocurricularNormalizeVapidKey(?string $key): string
{
    // Preserve URL-safe Base64 string directly as generated by Firebase Console
    return trim((string) $key);
}

/**
 * Return public Firebase web client configuration parameters.
 * No private keys or server credentials are contained in this array.
 */
function cocurricularGetFirebasePublicConfig(): array
{
    $rawVapid = defined('FIREBASE_VAPID_KEY') ? (string) FIREBASE_VAPID_KEY : (string) sms2_env('FIREBASE_VAPID_KEY', 'BAOUkvB4IfiTZltQ-Luku6yKX6BlEOFva_jFmHbDxJ2MB36MBL5uGjOH3xeIbIlIU6nyh6PtY6OIum3kA_SLQXM');
    return [
        'apiKey' => defined('FIREBASE_API_KEY') ? (string) FIREBASE_API_KEY : (string) sms2_env('FIREBASE_API_KEY', 'AIzaSyBBxVoH7mLn_u1xZwTywNczCdkMLfpXQqc'),
        'authDomain' => defined('FIREBASE_AUTH_DOMAIN') ? (string) FIREBASE_AUTH_DOMAIN : (string) sms2_env('FIREBASE_AUTH_DOMAIN', 'co-curricular-management-ed6aa.firebaseapp.com'),
        'projectId' => defined('FIREBASE_PROJECT_ID') ? (string) FIREBASE_PROJECT_ID : (string) sms2_env('FIREBASE_PROJECT_ID', 'co-curricular-management-ed6aa'),
        'storageBucket' => defined('FIREBASE_STORAGE_BUCKET') ? (string) FIREBASE_STORAGE_BUCKET : (string) sms2_env('FIREBASE_STORAGE_BUCKET', 'co-curricular-management-ed6aa.firebasestorage.app'),
        'messagingSenderId' => defined('FIREBASE_MESSAGING_SENDER_ID') ? (string) FIREBASE_MESSAGING_SENDER_ID : (string) sms2_env('FIREBASE_MESSAGING_SENDER_ID', '982710359986'),
        'appId' => defined('FIREBASE_APP_ID') ? (string) FIREBASE_APP_ID : (string) sms2_env('FIREBASE_APP_ID', '1:982710359986:web:bad1f738d2a5577bd0f6ab'),
        'vapidKey' => cocurricularNormalizeVapidKey($rawVapid),
    ];
}

/**
 * Create a database-backed notification for a Co-Curricular user.
 */
function cocurricularCreateNotification(array $data): ?int
{
    $userId = (int) ($data['user_id'] ?? 0);
    $title = trim((string) ($data['title'] ?? ''));
    $message = trim((string) ($data['message'] ?? ''));
    $type = trim((string) ($data['type'] ?? 'general'));
    $relatedId = isset($data['related_id']) ? (int) $data['related_id'] : null;
    $relatedModule = trim((string) ($data['related_module'] ?? 'cocurricular'));
    $destinationUrl = isset($data['destination_url']) ? trim((string) $data['destination_url']) : null;

    if ($userId <= 0 || $title === '' || $message === '') {
        return null;
    }

    $pdo = cocurricularDb();
    if (!$pdo) {
        return null;
    }

    try {
        $stmt = $pdo->prepare('
            INSERT INTO cocurricular_notifications
                (user_id, title, message, type, related_id, related_module, destination_url, is_read, created_at)
            VALUES
                (:user_id, :title, :message, :type, :related_id, :related_module, :destination_url, 0, NOW())
        ');
        $stmt->execute([
            ':user_id' => $userId,
            ':title' => $title,
            ':message' => $message,
            ':type' => $type,
            ':related_id' => $relatedId > 0 ? $relatedId : null,
            ':related_module' => $relatedModule !== '' ? $relatedModule : 'cocurricular',
            ':destination_url' => $destinationUrl !== '' ? $destinationUrl : null,
        ]);

        return (int) $pdo->lastInsertId();
    } catch (Throwable $e) {
        error_log('cocurricularCreateNotification error: ' . $e->getMessage());
        return null;
    }
}

/**
 * Fetch notifications for a specific user.
 */
function cocurricularGetUserNotifications(int $userId, int $limit = 20, bool $unreadOnly = false): array
{
    if ($userId <= 0) {
        return [];
    }

    $pdo = cocurricularDb();
    if (!$pdo) {
        return [];
    }

    try {
        $limit = max(1, min(100, $limit));
        $where = 'WHERE user_id = :user_id';
        if ($unreadOnly) {
            $where .= ' AND is_read = 0';
        }

        $stmt = $pdo->prepare("
            SELECT id, user_id, title, message, type, related_id, related_module, destination_url, is_read, read_at, created_at
            FROM cocurricular_notifications
            {$where}
            ORDER BY created_at DESC, id DESC
            LIMIT {$limit}
        ");
        $stmt->execute([':user_id' => $userId]);

        return $stmt->fetchAll() ?: [];
    } catch (Throwable $e) {
        error_log('cocurricularGetUserNotifications error: ' . $e->getMessage());
        return [];
    }
}

/**
 * Count unread notifications for a user.
 */
function cocurricularUnreadNotificationCount(int $userId): int
{
    if ($userId <= 0) {
        return 0;
    }

    $pdo = cocurricularDb();
    if (!$pdo) {
        return 0;
    }

    try {
        $stmt = $pdo->prepare('
            SELECT COUNT(*)
            FROM cocurricular_notifications
            WHERE user_id = :user_id AND is_read = 0
        ');
        $stmt->execute([':user_id' => $userId]);
        return (int) $stmt->fetchColumn();
    } catch (Throwable $e) {
        error_log('cocurricularUnreadNotificationCount error: ' . $e->getMessage());
        return 0;
    }
}

/**
 * Mark a notification as read for a specific user.
 */
function cocurricularMarkNotificationRead(int $notificationId, int $userId): bool
{
    if ($notificationId <= 0 || $userId <= 0) {
        return false;
    }

    $pdo = cocurricularDb();
    if (!$pdo) {
        return false;
    }

    try {
        $stmt = $pdo->prepare('
            UPDATE cocurricular_notifications
            SET is_read = 1, read_at = NOW()
            WHERE id = :id AND user_id = :user_id AND is_read = 0
        ');
        $stmt->execute([
            ':id' => $notificationId,
            ':user_id' => $userId,
        ]);

        return $stmt->rowCount() > 0;
    } catch (Throwable $e) {
        error_log('cocurricularMarkNotificationRead error: ' . $e->getMessage());
        return false;
    }
}

/**
 * Register or update an FCM device token for an authenticated user.
 */
function cocurricularRegisterFcmToken(int $userId, string $fcmToken, string $deviceType = 'web', ?string $userAgent = null): bool
{
    $fcmToken = trim($fcmToken);
    if ($userId <= 0 || $fcmToken === '') {
        return false;
    }

    $pdo = cocurricularDb();
    if (!$pdo) {
        return false;
    }

    try {
        $stmt = $pdo->prepare('
            INSERT INTO cocurricular_fcm_tokens
                (user_id, fcm_token, device_type, user_agent, is_active, last_used_at, created_at)
            VALUES
                (:user_id, :fcm_token, :device_type, :user_agent, 1, NOW(), NOW())
            ON DUPLICATE KEY UPDATE
                device_type = VALUES(device_type),
                user_agent = VALUES(user_agent),
                is_active = 1,
                last_used_at = NOW(),
                updated_at = NOW()
        ');
        $stmt->execute([
            ':user_id' => $userId,
            ':fcm_token' => $fcmToken,
            ':device_type' => substr(trim($deviceType), 0, 50) ?: 'web',
            ':user_agent' => $userAgent !== null ? substr(trim($userAgent), 0, 255) : null,
        ]);

        return true;
    } catch (Throwable $e) {
        error_log('cocurricularRegisterFcmToken error: ' . $e->getMessage());
        return false;
    }
}

/**
 * Deactivate an invalid or expired FCM token.
 */
function cocurricularDeactivateFcmToken(string $fcmToken): bool
{
    $fcmToken = trim($fcmToken);
    if ($fcmToken === '') {
        return false;
    }

    $pdo = cocurricularDb();
    if (!$pdo) {
        return false;
    }

    try {
        $stmt = $pdo->prepare('
            UPDATE cocurricular_fcm_tokens
            SET is_active = 0, updated_at = NOW()
            WHERE fcm_token = :fcm_token
        ');
        $stmt->execute([':fcm_token' => $fcmToken]);

        return $stmt->rowCount() > 0;
    } catch (Throwable $e) {
        error_log('cocurricularDeactivateFcmToken error: ' . $e->getMessage());
        return false;
    }
}

/**
 * Retrieve active FCM tokens for a list of user IDs.
 */
function cocurricularGetActiveFcmTokensForUsers(array $userIds): array
{
    $validUserIds = array_values(array_unique(array_filter(array_map('intval', $userIds), static fn(int $id): bool => $id > 0)));
    if (empty($validUserIds)) {
        return [];
    }

    $pdo = cocurricularDb();
    if (!$pdo) {
        return [];
    }

    try {
        $placeholders = implode(',', array_fill(0, count($validUserIds), '?'));
        $stmt = $pdo->prepare("
            SELECT id, user_id, fcm_token, device_type
            FROM cocurricular_fcm_tokens
            WHERE user_id IN ({$placeholders}) AND is_active = 1
        ");
        $stmt->execute($validUserIds);

        return $stmt->fetchAll() ?: [];
    } catch (Throwable $e) {
        error_log('cocurricularGetActiveFcmTokensForUsers error: ' . $e->getMessage());
        return [];
    }
}

/**
 * Format Co-Curricular notifications for UI payload consumption.
 */
function cocurricularNotificationPayloadForCurrentUser(int $limit = 20): array
{
    $userId = (int) getCurrentUserId();
    if ($userId <= 0) {
        return [];
    }

    $rows = cocurricularGetUserNotifications($userId, $limit);
    if (empty($rows)) {
        return [];
    }

    $baseUrl = defined('BASE_URL') ? (string) BASE_URL : '';

    return array_map(static function (array $row) use ($baseUrl): array {
        $created = strtotime((string) ($row['created_at'] ?? '')) ?: time();
        $isUnread = empty($row['is_read']);
        $type = (string) ($row['type'] ?? 'general');

        $icon = match ($type) {
            'membership_approved' => 'user-check',
            'membership_rejected' => 'user-x',
            'announcement_new' => 'bullhorn',
            'event_new' => 'calendar-event',
            'participation_approved' => 'circle-check',
            'participation_rejected' => 'circle-x',
            'attendance_open', 'attendance_reminder' => 'clock',
            'attendance_closed' => 'clock-off',
            default => 'bell',
        };

        $rawUrl = (string) ($row['destination_url'] ?? '');
        if ($rawUrl === '' || (!str_starts_with($rawUrl, '/') && !str_starts_with($rawUrl, 'http'))) {
            $rawUrl = '/modules/cocurricular/pages/my-club.php';
        }
        if (function_exists('smsNotificationAppUrl')) {
            $url = smsNotificationAppUrl($rawUrl);
        } else {
            $baseUrl = defined('BASE_URL') ? (string) BASE_URL : '';
            $url = rtrim($baseUrl, '/') . '/' . ltrim($rawUrl, '/');
        }

        $message = (string) ($row['message'] ?? '');

        return [
            'id' => (int) $row['id'],
            'batch_key' => 'cocurricular:' . (int) $row['id'],
            'icon' => $icon,
            'class' => 'text-primary',
            'label' => (string) ($row['title'] ?? 'Co-Curricular Notification'),
            'body' => $message,
            'preview' => mb_strlen($message) > 65 ? mb_substr($message, 0, 62) . '...' : $message,
            'status' => $isUnread ? 'unread' : 'read',
            'is_unread' => $isUnread,
            'time' => date('M j, Y h:i A', $created),
            'url' => $url,
            'destination_url' => $url,
            'type' => $type,
            'related_id' => (int) ($row['related_id'] ?? 0),
        ];
    }, $rows);
}

/**
 * Mark all Co-Curricular notifications as read for a specific user.
 */
function cocurricularMarkAllNotificationsRead(int $userId): bool
{
    if ($userId <= 0) {
        return false;
    }

    $pdo = cocurricularDb();
    if (!$pdo) {
        return false;
    }

    try {
        $stmt = $pdo->prepare('UPDATE cocurricular_notifications SET is_read = 1, read_at = NOW() WHERE user_id = :user_id AND is_read = 0');
        $stmt->execute([':user_id' => $userId]);
        return true;
    } catch (Throwable $e) {
        error_log('cocurricularMarkAllNotificationsRead error: ' . $e->getMessage());
        return false;
    }
}
